### ISSUE TITLE
[BUG] Unauthorized Redistribution False Positive

### ISSUE THREAD

**Issue by LordOfTheWeebs** [theomenden/TheOmenDen.WanderingCocoa#4]
**Describe the bug**
Simply reporting that there's a false positive in the unauthorized redistribution check.

**To Reproduce**
1. [Download the current latest Fabric release from CurseForge](https://www.curseforge.com/minecraft/mc-mods/wandering-cocoa/files/5692958).
2. Install the mod.
3. Load into a world.
4. See error.

**Expected behavior**
Nothing.

**Screenshots**
![2024-09-08_01 22 56](https://github.com/user-attachments/assets/f42265b4-dd68-449f-a851-61a92ac0fc58)
![Screenshot_20240908_013639](https://github.com/user-attachments/assets/10071237-82a8-46b4-ae30-f835b5a172b1)

**Desktop:**
 - OS: Nobara Linux 40
 - Java Version: OpenJDK 21.0.4 2024-07-16 (Red_Hat-21.0.4.0.7-2) (build 21.0.4+7, mixed mode, sharing)
 - Minecraft Version: 1.21.1 (Fabric Loader 0.16.5, Fabric API version 0.103.0+1.21.1, JamLib version 1.0.11+1.21, Architectury API version 13.0.6)

**Comment by AluTheCrow** [comment]
Thank you for pointing this out! I will fix this in the next release

**Comment by AluTheCrow** [comment]
Should be fixed in https://github.com/theomenden/TheOmenDen.WanderingCocoa/commit/808ed0fb9c8ead8b3f38f5a87902d4b477dfa9c2
